In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data.csv")
print(df)

              CountryName CountryCode  BirthRate  InternetUsers  \
0                   Aruba         ABW     10.244           78.9
1             Afghanistan         AFG     35.253            5.9
2                  Angola         AGO     45.985           19.1
3                 Albania         ALB     12.877           57.2
4    United Arab Emirates         ARE     11.044           88.0
..                    ...         ...        ...            ...
190           Yemen, Rep.         YEM     32.947           20.0
191          South Africa         ZAF     20.850           46.5
192      Congo, Dem. Rep.         COD     42.394            2.2
193                Zambia         ZMB     40.471           15.4
194              Zimbabwe         ZWE     35.715           18.5

             IncomeGroup
0            High income
1             Low income
2    Upper middle income
3    Upper middle income
4            High income
..                   ...
190  Lower middle income
191  Upper middle income
192           Low income
193  Lower middle income
194           Low income

[195 rows x 5 columns]

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
len(df)

195

In [10]:
df.columns
len(df.columns)

5

In [6]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [11]:
df.shape

(195, 5)

In [13]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [14]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [15]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [16]:
df[:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [17]:
df[:6]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income

In [19]:
df[3:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [20]:
df[0:50:5]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244          78.90          High income
5    Argentina         ARG     17.716          59.90          High income
10  Azerbaijan         AZE     18.300          58.70  Upper middle income
15  Bangladesh         BGD     20.142           6.63  Lower middle income
20     Belarus         BLR     12.500          54.17  Upper middle income
25    Barbados         BRB     12.188          73.00          High income
30      Canada         CAN     10.900          85.80          High income
35    Cameroon         CMR     37.236           6.40  Lower middle income
40  Costa Rica         CRI     15.022          45.96  Upper middle income
45     Germany         DEU      8.500          84.17          High income

In [21]:
df[::8]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
8,Australia,AUS,13.200,83.0000,High income
16,Bulgaria,BGR,9.200,53.0615,Upper middle income
24,Brazil,BRA,14.931,51.0400,Upper middle income
32,Chile,CHL,13.385,66.5000,High income
40,Costa Rica,CRI,15.022,45.9600,Upper middle income
48,Dominican Republic,DOM,21.198,45.9000,Upper middle income
56,Finland,FIN,10.700,91.5144,High income
64,Guinea,GIN,37.337,1.6000,Low income
72,Guam,GUM,17.389,65.4000,High income
80,India,IND,20.291,15.1000,Lower middle income
88,Jordan,JOR,27.046,41.0000,Upper middle income
96,Kuwait,KWT,20.575,75.4600,High income
104,Lesotho,LSO,28.738,5.0000,Lower middle income
112,Maldives,MDV,21.447,44.1000,Upper middle income
120,Mozambique,MOZ,39.705,5.4000,Low income
128,Nigeria,NGA,40.045,38.0000,Lower middle income
136,Panama,PAN,19.680,44.0300,Upper middle income
144,French Polynesia,PYF,16.393,56.8000,High income
152,Singapore,SGP,9.300,81.0000,High income
160,Suriname,SUR,18.455,37.4000,Upper middle income
168,Togo,TGO,36.080,4.5000,Low income
176,Turkey,TUR,16.836,46.2500,Upper middle income
184,"Venezuela, RB",VEN,19.842,54.9000,High income
192,"Congo, Dem. Rep.",COD,42.394,2.2000,Low income

In [22]:
df[::-10]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5000,Low income
184,"Venezuela, RB",VEN,19.842,54.9000,High income
174,Trinidad and Tobago,TTO,14.590,63.8000,High income
164,Swaziland,SWZ,30.093,24.7000,Lower middle income
154,Sierra Leone,SLE,36.729,1.7000,Low income
144,French Polynesia,PYF,16.393,56.8000,High income
134,Oman,OMN,20.419,66.4500,High income
124,Malaysia,MYS,16.805,66.9700,Upper middle income
114,"Macedonia, FYR",MKD,11.222,65.2400,Upper middle income
104,Lesotho,LSO,28.738,5.0000,Lower middle income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
84,Iceland,ISL,13.400,96.5468,High income
74,"Hong Kong SAR, China",HKG,7.900,74.2000,High income
64,Guinea,GIN,37.337,1.6000,Low income
54,Estonia,EST,10.300,79.4000,High income
44,Czech Republic,CZE,10.200,74.1104,High income
34,Cote d'Ivoire,CIV,37.320,8.4000,Lower middle income
24,Brazil,BRA,14.931,51.0400,Upper middle income
14,Burkina Faso,BFA,40.551,9.1000,Low income
4,United Arab Emirates,ARE,11.044,88.0000,High income

In [23]:
df[::-1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
191,South Africa,ZAF,20.850,46.5,Upper middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
...,...,...,...,...,...
4,United Arab Emirates,ARE,11.044,88.0,High income
3,Albania,ALB,12.877,57.2,Upper middle income
2,Angola,AGO,45.985,19.1,Upper middle income
1,Afghanistan,AFG,35.253,5.9,Low income
0,Aruba,ABW,10.244,78.9,High income

In [24]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [28]:
df_cat=df[['CountryName', 'CountryCode', 'IncomeGroup']]
df_cat.head(2)

   CountryName CountryCode  IncomeGroup
0        Aruba         ABW  High income
1  Afghanistan         AFG   Low income

In [29]:
df_num = df[['BirthRate','InternetUsers']]
df_num

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [30]:
print(df.shape)
print(df_num.shape)
print(df_cat.shape)

(195, 5)
(195, 2)
(195, 3)

In [31]:
print(df.columns)
print(df_num.columns)
print(df_cat.columns)

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')
Index(['BirthRate', 'InternetUsers'], dtype='object')
Index(['CountryName', 'CountryCode', 'IncomeGroup'], dtype='object')

In [32]:
df_cat.describe().T

            count unique          top freq
CountryName   195    195        Aruba    1
CountryCode   195    195          ABW    1
IncomeGroup   195      4  High income   67

In [33]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [34]:
df['InternetUsers']<2

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192    False
193    False
194    False
Name: InternetUsers, Length: 195, dtype: bool

In [35]:
len(df[df['BirthRate']>40])

12

In [36]:
#df[df['BirthRate']>40] & df[df['InternetUsers']<2]

df[(df.BirthRate > 40) & (df.InternetUsers < 2)]

    CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
11      Burundi         BDI     44.151            1.3  Low income
127       Niger         NER     49.661            1.7  Low income
156     Somalia         SOM     43.891            1.5  Low income

In [37]:
df['IncomeGroup'].unique()

array(['High income', 'Low income', 'Upper middle income',
       'Lower middle income'], dtype=object)

In [4]:
print("HELLO")

HELLO

In [5]:
print("ho")

ho